<?php

//@codingStandardsIgnoreFile

$hideCode = '';
if ($block->hideBuiltInPrintActions()) {
    $hideCode = ' style="display:none;"';
}

?>
<?php $_order = $block->getOrder() ?>
<div class="actions-toolbar"<?php echo $hideCode ?>>
    <a href="<?php /* @escapeNotVerified */ echo $block->getPrintAllCreditmemosUrl($_order) ?>"
       onclick="this.target='_blank'"
       class="action print">
        <span><?php /* @escapeNotVerified */ echo __('Print All Refunds') ?></span>
    </a>
</div>
<?php foreach ($_order->getCreditmemosCollection() as $_creditmemo): ?>
<div class="order-title">
    <strong><?php /* @escapeNotVerified */ echo __('Refund #') ?><?php /* @escapeNotVerified */ echo $_creditmemo->getIncrementId(); ?> </strong>
    <a href="<?php /* @escapeNotVerified */ echo $block->getPrintCreditmemoUrl($_creditmemo) ?>"
       onclick="this.target='_blank'"
       class="action print"<?php echo $hideCode ?>>
        <span><?php /* @escapeNotVerified */ echo __('Print Refund') ?></span>
    </a>
    <?php if($block->addPDFLink($_creditmemo)):?>
        <a href="<?php /* @escapeNotVerified */ echo  $block->getPrintPDFUrl($_creditmemo) ?>"
           onclick="this.target='_blank'"
           class="action">
            <span><?php /* @escapeNotVerified */ echo __('Print Credit Memo PDF') ?></span>
        </a>
    <?php endif?>
</div>

<div class="table-wrapper order-items-creditmemo">
    <table class="data table table-order-items creditmemo" id="my-refund-table-<?php /* @escapeNotVerified */ echo $_creditmemo->getId(); ?>">
        <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Items Refunded') ?></caption>
        <thead>
            <tr>
                <th class="col name"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
                <th class="col sku"><?php /* @escapeNotVerified */ echo __('SKU') ?></th>
                <th class="col price"><?php /* @escapeNotVerified */ echo __('Price') ?></th>
                <th class="col qty"><?php /* @escapeNotVerified */ echo __('Qty') ?></th>
                <th class="col subtotal"><?php /* @escapeNotVerified */ echo __('Subtotal') ?></th>
                <th class="col discount"><?php /* @escapeNotVerified */ echo __('Discount Amount') ?></th>
                <th class="col total"><?php /* @escapeNotVerified */ echo __('Row Total') ?></th>
            </tr>
        </thead>
        <?php $_items = $_creditmemo->getAllItems(); ?>
        <?php $_count = count($_items) ?>
        <?php foreach ($_items as $_item): ?>
        <?php if ($_item->getOrderItem()->getParentItem()) {
    continue;
} ?>
        <tbody>
            <?php echo $block->getItemHtml($_item) ?>
        </tbody>
        <?php endforeach; ?>
        <tfoot>
            <?php echo $block->getTotalsHtml($_creditmemo);?>
        </tfoot>
    </table>
</div>
<?php echo $block->getCommentsHtml($_creditmemo)?>
<?php endforeach; ?>

<?php if ($block->hideBuiltInPrintActions()): ?>
<style type="text/css">
    .order-actions-toolbar .action.print {
        display: none !important;
    }
</style>
<?php endif; ?>