<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php 
$_product = $block->getProduct(); 
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper         = $this->helper('Magento\Catalog\Helper\Product\Compare');
$_config               = $this->helper('Sm\Market\Helper\Data');
?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">

        <?php if ($block->shouldRenderQuantity()): ?>
            <div class="quantity-wrap">
                <div class="quantity-left"><?php echo __('Quantity') ?></div>
                <div class="quantity-right">
                    <div class="control-qty control control-qty-cart">
                        <span class="quantity-controls quantity-minus"></span>
                        <input type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               value="<?php /* @escapeNotVerified */
                               echo $block->getProductDefaultQty() * 1 ?>"
                               title="<?php /* @escapeNotVerified */
                               echo __('Qty') ?>" class="qty-default input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                        <span class="quantity-controls quantity-plus"></span>                          
                        <script type="text/javascript">
                            require([
                                'jquery'
                            ], function ($) {
                                $('.quantity-plus').click(function () {
                                    var qty = Number($('.qty-default').val()) + 1;
                                    $('.qty-default').val(qty);

                                    var price = $('.price-wrap').find('.price').html();
                                    var currency = price.charAt(0);
                                    price = price.slice(1);
                                    price = (price * qty).toFixed(2);
                                    $('.total-price').html(currency+price);
                                    $('.total-price-div').show();
                                });

                                $('.quantity-minus').click(function () {
                                    var value = Number($('.qty-default').val()) - 1;
                                    if (value > 0) {
                                        $('.qty-default').val(value);

                                        var price = $('.price-wrap').find('.price').html();
                                        var currency = price.charAt(0);
                                        price = price.slice(1);
                                        price = (price * value).toFixed(2);
                                        $('.total-price').html(currency+price);
                                    }

                                    if(value == 1){
                                        $('.total-price-div').hide();
                                    }

                                });

                                $('.qty-default').on('input', function () {
                                    var qty = $(this).val();
                                    if(qty > 1){
                                        var price = $('.price-wrap').find('.price').html();
                                        var currency = price.charAt(0);
                                        price = price.slice(1);
                                        price = (price * qty).toFixed(2);
                                        $('.total-price').html(currency+price);
                                        $('.total-price-div').show();
                                    } else {
                                        $('.total-price-div').hide();
                                    }
                                });

                            });
                        </script>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <div class="price-wrap total-price-div" style="display: none;">
            <div class="price-left"><?php echo __('Total Price') ?></div>
            <div class="price-right">
                <div class="price-container price-final_price tax weee">
                    <span class="total-price"></span>
                </div>
            </div>
        </div>

        <div class="allbtn-wrap">
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */
                        echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */
                    echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>

            <div class="product-addto-links" data-role="add-to-links">
                <?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                        <a title="<?php echo __('Add to Wish List'); ?>" href="#"
                        class="action towishlist"
                        data-post='<?php /* @escapeNotVerified */
                        echo $_wishlistSubmitParams; ?>'
                        data-action="add-to-wishlist"><span><?php /* @escapeNotVerified */
                                echo __('Add to Wish List') ?></span></a>
                    <?php endif; ?>
                <?php } ?>

                <?php if ($_config->getAdvanced('show_compare_button')) { ?>
                    <a title="<?php echo __('Add to Compare'); ?>" href="#" data-post='<?php /* @escapeNotVerified */
                    echo $compareHelper->getPostDataParams($_product); ?>' data-role="add-to-links" class="action tocompare">
                        <span><?php /* @escapeNotVerified */
                            echo __('Add to Compare') ?></span>
                    </a>
                <?php } ?>
            </div>
            <div class="addthis_inline_share_toolbox"></div>

        </div>
    </div>
    <script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @escapeNotVerified */
    echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions()) ?>
        }
    }


</script>
<?php else: ?>
    <?php $buttonTitle = __('Out of stock'); ?>
    <div class="box-tocart">
        <div class="allbtn-wrap">
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */
                        echo $buttonTitle ?>"
                        class="action primary">
                <span><?php /* @escapeNotVerified */
                    echo $buttonTitle ?></span>
                </button>
            </div>

            <div class="product-addto-links" data-role="add-to-links">
                <?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                        <a title="<?php echo __('Add to Wish List'); ?>" href="#"
                        class="action towishlist"
                        data-post='<?php /* @escapeNotVerified */
                        echo $_wishlistSubmitParams; ?>'
                        data-action="add-to-wishlist"><span><?php /* @escapeNotVerified */
                                echo __('Add to Wish List') ?></span></a>
                    <?php endif; ?>
                <?php } ?>

                <?php if ($_config->getAdvanced('show_compare_button')) { ?>
                    <a title="<?php echo __('Add to Compare'); ?>" href="#" data-post='<?php /* @escapeNotVerified */
                    echo $compareHelper->getPostDataParams($_product); ?>' data-role="add-to-links" class="action tocompare">
                        <span><?php /* @escapeNotVerified */
                            echo __('Add to Compare') ?></span>
                    </a>
                <?php } ?>
            </div>
            <div class="addthis_inline_share_toolbox"></div>

        </div>
    </div>
<?php endif; ?>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });
        });
    </script>
<?php else : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }

    
    </script>
<?php endif; ?>