<?php
/** @author Salman Hanif
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form contact"
      action="https://lofcart.com/contact_prod/index/send"
      id="contact-form"
      method="post"
      data-hasrequired="<?php echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo __('WRITE US YOUR SPECIAL REQUEST') ?></span></legend><br /><hr>
        <div class="fieldset row">
            <div class="fields col-md-6">
                <div class="field name required">
                    <div class="control">
                        <input placeholder="Name" name="name" id="name" title="<?php echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="field email required">
                    <div class="control">
                        <input placeholder="Email" name="email" id="email" title="<?php echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
            </div>
            <div class="fields col-md-6">
                <div class="field comment required">
                    <div class="control">
                        <textarea placeholder="Hello, may I please request for more quantity on this product?" name="comment" id="comment" title="<?php echo __('Any Comments/Message?') ?>" class="input-text" cols="5" rows="8" data-validate="{required:true}"></textarea>
                    </div>
                </div>
                <?php echo $block->getChildHtml('form.additional.info'); ?>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary">
                <span><?php echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
