<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert'
    ], function ($, alert) {
        window.abzertechSmtpAppDebugTest = function () {
            var postData = {form_key: FORM_KEY};
            //global var configForm
            configForm.find('[id^=abzer_smtp_general]').find(':input').serializeArray().map(function (field) {
                var name = field.name.match(/groups\[general\]?(\[groups\]\[debug\])?\[fields\]\[(.*)\]\[value]/);
                
                if (name && name.length === 3) {
                    postData[name[2]] = field.value;
                }
            });

            $.ajax({
                url: ' <?=  /* @noEscape */ $block->getAdminUrl() ?>',
                type: 'post',
                dataType: 'html',
                data: postData,
                showLoader: true
            }).done(function (response) {
                if (typeof response === 'object') {
                    if (response.error) {
                        alert({title: 'Error', content: response.message});
                    } else if (response.ajaxExpired) {
                        window.location.href = response.ajaxRedirect;
                    }
                } else {
                    alert({
                        title: '',
                        content: response,
                        buttons: []
                    });
                }

            });
        }
    });
</script>

<?= $block->getButtonHtml() ?>
